


PHONY: plots

# $(MAKE) -c switched to subdir so that all pathing works out as if i ran it normally, then calls make 
plots: 
	$(MAKE) -C high_order_sod_shock_tube_plots &&\
	$(MAKE) -C low_order_sod_shock_tube_plots
